CI: update toolchain to v1.53.0
While building the package, we need to include the `time' crate.
But, used version needs a specific Cargo feature, mainly the `resolver'.
We can find this feature in v1.51.0.  But, other features needed in the
in-between versions block the build.

The error message we get during build is:

   Downloaded time v0.3.6
   error: failed to parse manifest at `/time-0.3.6/Cargo.toml`

   Caused by:
     feature `resolver` is required

     this Cargo does not support nightly features, but if you
     switch to nightly channel you can add
     `cargo-features = ["resolver"]` to enable this feature