CI: use Rust v1.49.0 to build project
The project depends on the crate `socket', which needs a recent version
of the Rust compiler.  Otherwise, the following error is emitted:

   error[E0658]: `match` is not allowed in a `const fn`

Another error reported is:

   error[E0658]: unions with non-`Copy` fields are unstable

This one comes from the `want' crate.